### ISSUE TITLE
Using curly brackets to represent blocks of code instead of parentheses

### ISSUE THREAD

**Issue by icositetrachoron-programmer** [DPLA-S/DPLA-S.github.io#1]
In most programming languages, parentheses are used to pass arguments and give precedence to an expression. However, DPLA uses parentheses to group blocks of code, which is unconventional. I would suggest replacing the parentheses with curly brackets to group blocks of code.
So
```
Event['onload']:(
   
)
```
would become
```
Event['onload']:{
   
}
```

**Comment by Daniel4-Scratch** [comment]
Thanks for the issue, this is a good one!
I'm fighting about this myself, here's why: 
(): I want my language to be different from others most programs.
But then
{}: I want to follow what most popular programs do.

**Comment by Daniel4-Scratch** [comment]
and I am mostly going for the brackets

**Comment by Daniel4-Scratch** [comment]
Thanks for the help, but i'm sticking with the brackets. 
And you mess the code up a bit; it is not `event['onLaunch']` it is `event[onlaunch]` 😉 :.
